version: '3.7'

services: 
  saudemais_database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: saudemais_database
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "01075783"
      MYSQL_DATABASE: "doctors"
    volumes:
      - my-datavolume:/var/lib/mysql
    networks: 
      - link
  
  app:
    build: .
    container_name: saudemais_api
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/app/saudemais
    depends_on: 
      - saudemais_database  
    networks: 
      - link

networks: 
  link:
    
volumes:
  my-datavolume: